[{
    "couponCode": {
        "platformCouponCode": "M40SEJULY",
        "useCouponCode": true,
        "showCouponCodeInputBox": true,
        "couponCodeAmount": {
            "amount": {
                "cent": 3459,
                "currency": "EUR",
                "currencyCode": "EUR",
                "centFactor": 100,
                "amount": 34.59
            },
            "amountLocal": {
                "cent": 3459,
                "currency": "EUR",
                "currencyCode": "EUR",
                "centFactor": 100,
                "amount": 34.59
            },
            "formatted": "€ 34,59",
            "formattedLocal": "€ 34,59"
        },
        "couponCodeResultCode": "1",
        "couponCodeWarnMsg": "Code applied successfully.",
        "couponCodeWarnTitle": "Apply AliExpress Coupon:"
    },
}]


"couponCode": {
    "platformCouponCode": null,
        "useCouponCode": false,
            "showCouponCodeInputBox": true,
                "couponCodeAmount": null,
                    "couponCodeResultCode": null,
                        "couponCodeWarnMsg": "Please enter a valid promo code.",
                            "couponCodeWarnTitle": null
},